import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SearchUrl from '../components/SearchUrl'

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100 min-h-screen py-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchUrl/>
    </div>
  )
}

export default Home
